name: admin_app
description: Admin for management
author: Store pattern team <meomeocf98@gmail.com>
homepage: https://github.com/uiters/store-pattern
repository: https://github.com/uiters/store-pattern

version: 1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: 0.12.1
  dbcrypt: 1.0.0
  image_picker: 0.6.7+3
  charts_flutter: 0.9.0
  ansicolor: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis/Dosis-Regular.ttf
          weight: 400
        - asset: assets/fonts/Dosis/Dosis-Medium.ttf
          weight: 500
        - asset: assets/fonts/Dosis/Dosis-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Dosis/Dosis-Bold.ttf
          weight: 800
        - asset: assets/fonts/Dosis/Dosis-ExtraBold.ttf
          weight: 900
